//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class address_x_organization
    {
        public System.Guid oxa_key { get; set; }
        public Nullable<System.Guid> oxa_adr_key { get; set; }
        public Nullable<System.Guid> oxa_org_key { get; set; }
        public Nullable<byte> oxa_delete_flag { get; set; }
        public string oxa_add_user { get; set; }
        public Nullable<System.DateTime> oxa_add_date { get; set; }
        public string oxa_change_user { get; set; }
        public Nullable<System.DateTime> oxa_change_date { get; set; }
    
        public virtual co_address co_address { get; set; }
        public virtual co_organization co_organization { get; set; }
    }
}
