//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class address_x_contact
    {
        public System.Guid cxa_key { get; set; }
        public Nullable<System.Guid> cxa_adr_key { get; set; }
        public Nullable<System.Guid> cxa_ct_key { get; set; }
        public Nullable<byte> cxa_delete_flag { get; set; }
        public string cxa_add_user { get; set; }
        public Nullable<System.DateTime> cxa_add_date { get; set; }
        public string cxa_change_date { get; set; }
        public Nullable<System.DateTime> cxa_change_user { get; set; }
    
        public virtual co_contact co_contact { get; set; }
        public virtual co_address co_address { get; set; }
    }
}
