//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attachment_x_organization
    {
        public System.Guid axo_key { get; set; }
        public Nullable<System.Guid> axo_rfa_key { get; set; }
        public Nullable<System.Guid> axo_org_key { get; set; }
    }
}
