//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class co_address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public co_address()
        {
            this.address_x_contact = new HashSet<address_x_contact>();
            this.address_x_organization = new HashSet<address_x_organization>();
        }
    
        public System.Guid adr_key { get; set; }
        public Nullable<byte> adr_mailing_flag { get; set; }
        public Nullable<byte> adr_shipping_flag { get; set; }
        public Nullable<byte> adr_headquarter_flag { get; set; }
        public Nullable<byte> adr_billing_flag { get; set; }
        public string adr_email { get; set; }
        public string adr_line1 { get; set; }
        public string adr_line2 { get; set; }
        public string adr_line3 { get; set; }
        public string adr_city { get; set; }
        public string adr_state { get; set; }
        public string adr_county { get; set; }
        public string adr_zip { get; set; }
        public string adr_country { get; set; }
        public string adr_province { get; set; }
        public Nullable<byte> adr_delete_flag { get; set; }
        public string adr_add_user { get; set; }
        public Nullable<System.DateTime> adr_add_date { get; set; }
        public string adr_change_user { get; set; }
        public Nullable<System.DateTime> adr_change_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<address_x_contact> address_x_contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<address_x_organization> address_x_organization { get; set; }
    }
}
