//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class co_contact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public co_contact()
        {
            this.address_x_contact = new HashSet<address_x_contact>();
            this.co_page_view = new HashSet<co_page_view>();
            this.co_permission = new HashSet<co_permission>();
            this.contact_x_organization = new HashSet<contact_x_organization>();
            this.contact_x_product = new HashSet<contact_x_product>();
            this.contact_x_request = new HashSet<contact_x_request>();
            this.contact_x_RACI = new HashSet<contact_x_RACI>();
            this.contact_x_response = new HashSet<contact_x_response>();
            this.rfp_event_invitee = new HashSet<rfp_event_invitee>();
            this.rfp_respond_invitation = new HashSet<rfp_respond_invitation>();
            this.rfp_score = new HashSet<rfp_score>();
            this.rfp_validation_reference = new HashSet<rfp_validation_reference>();
            this.rfp_event = new HashSet<rfp_event>();
        }
    
        public System.Guid ct_key { get; set; }
        public Nullable<long> ct_id { get; set; }
        public string ct_first_name { get; set; }
        public string ct_last_name { get; set; }
        public string ct_email { get; set; }
        public string ct_phone { get; set; }
        public string ct_fax { get; set; }
        public string ct_password { get; set; }
        public Nullable<byte> ct_delete_flag { get; set; }
        public Nullable<System.DateTime> ct_add_date { get; set; }
        public string ct_add_user { get; set; }
        public Nullable<System.DateTime> ct_change_date { get; set; }
        public string ct_change_user { get; set; }
        public Nullable<System.Guid> ct_activation_code { get; set; }
        public Nullable<byte> ct_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<address_x_contact> address_x_contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<co_page_view> co_page_view { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<co_permission> co_permission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contact_x_organization> contact_x_organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contact_x_product> contact_x_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contact_x_request> contact_x_request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contact_x_RACI> contact_x_RACI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contact_x_response> contact_x_response { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rfp_event_invitee> rfp_event_invitee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rfp_respond_invitation> rfp_respond_invitation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rfp_score> rfp_score { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rfp_validation_reference> rfp_validation_reference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rfp_event> rfp_event { get; set; }
    }
}
