//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class co_favourite
    {
        public System.Guid fav_key { get; set; }
        public Nullable<System.Guid> fav_org_key { get; set; }
        public Nullable<System.Guid> fav_prd_key { get; set; }
        public Nullable<System.Guid> fav_rfp_key { get; set; }
        public Nullable<System.DateTime> fav_add_date { get; set; }
        public string fav_add_user { get; set; }
        public Nullable<System.DateTime> fav_change_date { get; set; }
        public string fav_change_user { get; set; }
    
        public virtual co_organization co_organization { get; set; }
        public virtual rfp_product rfp_product { get; set; }
        public virtual rfp_request rfp_request { get; set; }
    }
}
