//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class co_permission
    {
        public System.Guid per_key { get; set; }
        public System.Guid per_ct_key { get; set; }
        public string per_type { get; set; }
        public string per_RACI { get; set; }
        public Nullable<byte> per_delete_flag { get; set; }
        public Nullable<System.DateTime> per_add_date { get; set; }
        public string per_add_user { get; set; }
        public Nullable<System.DateTime> per_change_date { get; set; }
        public string per_change_user { get; set; }
    
        public virtual co_contact co_contact { get; set; }
    }
}
