//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class co_page_view
    {
        public System.Guid pv_key { get; set; }
        public Nullable<System.Guid> pv_rfp_key { get; set; }
        public Nullable<System.Guid> pv_prd_key { get; set; }
        public Nullable<System.Guid> pv_source_ct_key { get; set; }
        public Nullable<long> pv_page_id { get; set; }
        public Nullable<System.DateTime> pv_view_datetime { get; set; }
        public string pv_add_user { get; set; }
    
        public virtual co_contact co_contact { get; set; }
        public virtual rfp_product rfp_product { get; set; }
        public virtual rfp_request rfp_request { get; set; }
    }
}
