//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_x_organization
    {
        public System.Guid cxo_key { get; set; }
        public System.Guid cxo_org_key { get; set; }
        public Nullable<System.Guid> cxo_ct_key { get; set; }
        public string cxo_rlt_code { get; set; }
        public string cxo_title { get; set; }
        public Nullable<System.DateTime> cxo_start_date { get; set; }
        public Nullable<System.DateTime> cxo_end_date { get; set; }
        public Nullable<byte> cxo_delete_flag { get; set; }
        public Nullable<System.DateTime> cxo_add_date { get; set; }
        public string cxo_add_user { get; set; }
        public Nullable<System.DateTime> cxo_change_date { get; set; }
        public string cxo_change_user { get; set; }
    
        public virtual co_contact co_contact { get; set; }
        public virtual co_organization co_organization { get; set; }
    }
}
