//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_x_response
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contact_x_response()
        {
            this.rfp_attachment = new HashSet<rfp_attachment>();
        }
    
        public System.Guid cxr_key { get; set; }
        public Nullable<System.Guid> cxr_rfr_key { get; set; }
        public Nullable<System.Guid> cxr_ct_key { get; set; }
        public string cxr_rlt_code { get; set; }
        public string cxr_title { get; set; }
        public Nullable<byte> cxr_delete_flag { get; set; }
        public Nullable<System.DateTime> cxr_add_date { get; set; }
        public string cxr_add_user { get; set; }
        public Nullable<System.DateTime> cxr_change_date { get; set; }
        public string cxr_change_user { get; set; }
    
        public virtual co_contact co_contact { get; set; }
        public virtual rfp_response rfp_response { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rfp_attachment> rfp_attachment { get; set; }
    }
}
