//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_x_request
    {
        public System.Guid cxp_key { get; set; }
        public Nullable<System.Guid> cxp_ct_key { get; set; }
        public Nullable<System.Guid> cxp_rfp_key { get; set; }
        public string cxp_rlt_code { get; set; }
        public string cxp_title { get; set; }
        public string cxp_staff_yr_experience_related { get; set; }
        public string cxp_staff_yr_experience_total { get; set; }
        public string cxp_staff_experience_decription { get; set; }
        public Nullable<byte> cxp_delete_flag { get; set; }
        public Nullable<System.DateTime> cxp_add_date { get; set; }
        public string cxp_add_user { get; set; }
        public Nullable<System.DateTime> cxp_change_date { get; set; }
        public string cxp_change_user { get; set; }
    
        public virtual co_contact co_contact { get; set; }
        public virtual rfp_request rfp_request { get; set; }
    }
}
