//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkup_population
    {
        public System.Guid lk1_key { get; set; }
        public Nullable<int> lk1_code { get; set; }
        public string lk1_description { get; set; }
    }
}
