//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkup_cxr_rlt_code
    {
        public System.Guid lk2_key { get; set; }
        public string lk2_code { get; set; }
        public string lk2_description { get; set; }
    }
}
