//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class organization_x_request
    {
        public System.Guid oxr_key { get; set; }
        public Nullable<System.Guid> oxr_org_key { get; set; }
        public Nullable<System.Guid> oxr_rfp_key { get; set; }
    }
}
