//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rfp_timeline_master_template
    {
        public System.Guid time_key { get; set; }
        public string time_timeline_description { get; set; }
        public string time_procurement_workflow { get; set; }
        public string time_vendor_workflow { get; set; }
        public Nullable<decimal> time_reminder_value { get; set; }
        public Nullable<decimal> time_order { get; set; }
        public Nullable<byte> time_delete_flag { get; set; }
        public Nullable<System.DateTime> time_add_date { get; set; }
        public string time_add_user { get; set; }
        public Nullable<System.DateTime> time_change_date { get; set; }
        public string time_change_user { get; set; }
    }
}
