//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rfp_validation_reference
    {
        public System.Guid vr_key { get; set; }
        public Nullable<System.Guid> vr_prd_key { get; set; }
        public Nullable<System.Guid> vr_org_key { get; set; }
        public Nullable<System.Guid> vr_rfp_key { get; set; }
        public Nullable<System.Guid> vr_ct_key { get; set; }
        public string vr_customer_name { get; set; }
        public string vr_description { get; set; }
        public Nullable<byte> vr_delete_flag { get; set; }
        public Nullable<System.DateTime> vr_add_date { get; set; }
        public string vr_add_user { get; set; }
        public Nullable<System.DateTime> vr_change_date { get; set; }
        public string vr_change_user { get; set; }
    
        public virtual co_contact co_contact { get; set; }
        public virtual co_organization co_organization { get; set; }
        public virtual rfp_product rfp_product { get; set; }
        public virtual rfp_request rfp_request { get; set; }
    }
}
