//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rfp_sop_section
    {
        public System.Guid sec_key { get; set; }
        public string sec_solution { get; set; }
        public string sec_requirements { get; set; }
        public Nullable<byte> sec_delete_flag { get; set; }
        public string sec_add_user { get; set; }
        public Nullable<System.DateTime> sec_add_date { get; set; }
        public string sec_change_user { get; set; }
        public Nullable<System.DateTime> sec_change_date { get; set; }
    }
}
