//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rfp_attachment
    {
        public System.Guid rfa_key { get; set; }
        public Nullable<System.Guid> rfa_rfp_key { get; set; }
        public Nullable<System.Guid> rfa_rfr_key { get; set; }
        public Nullable<System.Guid> rfa_cxr_key { get; set; }
        public Nullable<System.Guid> rfa_prd_key { get; set; }
        public Nullable<System.Guid> rfa_org_key { get; set; }
        public string rfa_file_name { get; set; }
        public string rfa_file_path { get; set; }
        public string rfa_type { get; set; }
        public string rfa_mime { get; set; }
        public byte[] rfa_attachment { get; set; }
        public Nullable<byte> rfa_delete_flag { get; set; }
        public string rfa_add_user { get; set; }
        public Nullable<System.DateTime> rfa_add_date { get; set; }
        public string rfa_change_user { get; set; }
        public Nullable<System.DateTime> rfa_change_date { get; set; }
    
        public virtual co_organization co_organization { get; set; }
        public virtual contact_x_response contact_x_response { get; set; }
        public virtual rfp_request rfp_request { get; set; }
        public virtual rfp_response rfp_response { get; set; }
        public virtual rfp_product rfp_product { get; set; }
    }
}
