//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rfp_score
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rfp_score()
        {
            this.rfp_score_rules = new HashSet<rfp_score_rules>();
        }
    
        public System.Guid rfs_key { get; set; }
        public Nullable<System.Guid> rfs_rfr_key { get; set; }
        public Nullable<System.Guid> rfs_ct_key { get; set; }
        public string rfs_score { get; set; }
        public string rfs_comment { get; set; }
        public Nullable<byte> rfs_delete_key { get; set; }
        public Nullable<System.DateTime> rfs_add_date { get; set; }
        public string rfs_add_user { get; set; }
        public Nullable<System.DateTime> rfs_change_date { get; set; }
        public string rfs_change_user { get; set; }
    
        public virtual co_contact co_contact { get; set; }
        public virtual rfp_response rfp_response { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rfp_score_rules> rfp_score_rules { get; set; }
    }
}
