//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rfp_score_rules
    {
        public System.Guid eva_key { get; set; }
        public Nullable<System.Guid> eva_rfs_key { get; set; }
        public Nullable<System.Guid> eva_rfp_key { get; set; }
        public string eva_criteria_name { get; set; }
        public string eva_criteria_description { get; set; }
        public string eva_score_method { get; set; }
        public Nullable<int> eva_point_max { get; set; }
        public Nullable<decimal> eva_weight { get; set; }
        public Nullable<byte> eva_delete_flag { get; set; }
        public Nullable<System.DateTime> eva_add_date { get; set; }
        public string eva_add_user { get; set; }
        public Nullable<System.DateTime> eva_change_date { get; set; }
        public string eva_change_user { get; set; }
    
        public virtual rfp_request rfp_request { get; set; }
        public virtual rfp_score rfp_score { get; set; }
    }
}
