//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rfp_response
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rfp_response()
        {
            this.contact_x_response = new HashSet<contact_x_response>();
            this.rfp_attachment = new HashSet<rfp_attachment>();
            this.rfp_score = new HashSet<rfp_score>();
        }
    
        public System.Guid rfr_key { get; set; }
        public Nullable<System.Guid> rfr_org_key { get; set; }
        public Nullable<System.Guid> rfr_rfp_key { get; set; }
        public Nullable<long> rfr_id { get; set; }
        public string rfr_sow { get; set; }
        public string rfr_pricing { get; set; }
        public string rfr_statement_of_interest { get; set; }
        public Nullable<byte> rfr_awarded { get; set; }
        public Nullable<System.DateTime> rfr_awarded_date { get; set; }
        public Nullable<byte> rfr_delete_flag { get; set; }
        public Nullable<System.DateTime> rfr_add_date { get; set; }
        public string rfr_add_user { get; set; }
        public Nullable<System.DateTime> rfr_change_date { get; set; }
        public string rfr_change_user { get; set; }
    
        public virtual co_organization co_organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contact_x_response> contact_x_response { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rfp_attachment> rfp_attachment { get; set; }
        public virtual rfp_request rfp_request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rfp_score> rfp_score { get; set; }
    }
}
