//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rfp_page
    {
        public System.Guid pag_key { get; set; }
        public Nullable<System.Guid> pag_rfp_key { get; set; }
        public Nullable<System.Guid> pag_org_key { get; set; }
        public string pag_content_type { get; set; }
        public string pag_content { get; set; }
        public Nullable<byte> pag_delete_flag { get; set; }
        public string pag_add_user { get; set; }
        public Nullable<System.DateTime> pag_add_date { get; set; }
        public string pag_change_user { get; set; }
        public Nullable<System.DateTime> pag_change_date { get; set; }
    
        public virtual co_organization co_organization { get; set; }
        public virtual rfp_request rfp_request { get; set; }
    }
}
