//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rfp_task
    {
        public System.Guid rft_key { get; set; }
        public Nullable<System.Guid> rft_rfp_key { get; set; }
        public Nullable<long> rft_id { get; set; }
        public string rft_description { get; set; }
        public Nullable<System.DateTime> rft_question_answer_date { get; set; }
        public Nullable<System.DateTime> rft_vendor_meeting_date { get; set; }
        public Nullable<System.DateTime> rft_scoring_date { get; set; }
        public Nullable<System.DateTime> rft_negotiation_date { get; set; }
        public Nullable<byte> rft_delete_flag { get; set; }
        public Nullable<System.DateTime> rft_add_date { get; set; }
        public string rft_add_user { get; set; }
        public Nullable<System.DateTime> rft_change_date { get; set; }
        public string rft_change_user { get; set; }
    
        public virtual rfp_request rfp_request { get; set; }
    }
}
