//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rfp_vendor_allowance
    {
        public System.Guid va_key { get; set; }
        public Nullable<System.Guid> va_org_key { get; set; }
        public string va_model { get; set; }
        public Nullable<byte> va_delete_flag { get; set; }
        public Nullable<System.DateTime> va_add_date { get; set; }
        public string va_add_user { get; set; }
        public Nullable<System.DateTime> va_change_date { get; set; }
        public string va_change_user { get; set; }
    
        public virtual co_organization co_organization { get; set; }
    }
}
