//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rfp_question
    {
        public System.Guid qst_id { get; set; }
        public Nullable<System.Guid> qst_rfp_id { get; set; }
        public Nullable<int> qst_number { get; set; }
        public string qst_question_header { get; set; }
        public string qst_question_detail { get; set; }
    }
}
