//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rfp_product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rfp_product()
        {
            this.co_favourite = new HashSet<co_favourite>();
            this.co_page_view = new HashSet<co_page_view>();
            this.contact_x_product = new HashSet<contact_x_product>();
            this.contact_x_RACI = new HashSet<contact_x_RACI>();
            this.product_x_request = new HashSet<product_x_request>();
            this.rfp_attachment = new HashSet<rfp_attachment>();
            this.rfp_validation_reference = new HashSet<rfp_validation_reference>();
        }
    
        public System.Guid prd_key { get; set; }
        public Nullable<System.Guid> prd_org_key { get; set; }
        public string prd_name { get; set; }
        public Nullable<int> prd_type { get; set; }
        public Nullable<int> prd_subtype { get; set; }
        public string prd_description { get; set; }
        public string prd_benefits { get; set; }
        public string prd_use_cases { get; set; }
        public string prd_pricing { get; set; }
        public string prd_features { get; set; }
        public string prd_website { get; set; }
        public string prd_target_users { get; set; }
        public Nullable<byte> prd_delete_flag { get; set; }
        public Nullable<System.DateTime> prd_add_date { get; set; }
        public string prd_add_user { get; set; }
        public Nullable<System.DateTime> prd_change_date { get; set; }
        public string prd_change_user { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<co_favourite> co_favourite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<co_page_view> co_page_view { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contact_x_product> contact_x_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contact_x_RACI> contact_x_RACI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_x_request> product_x_request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rfp_attachment> rfp_attachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rfp_validation_reference> rfp_validation_reference { get; set; }
    }
}
