//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rfp_timeline_org_template
    {
        public System.Guid tio_key { get; set; }
        public Nullable<System.Guid> tio_org_key { get; set; }
        public string tio_time_timeline_description { get; set; }
        public string tio_new_description { get; set; }
        public string tio_time_procurement_workflow { get; set; }
        public string tio_time_vendor_workflow { get; set; }
        public Nullable<decimal> tio_time_reminder_value { get; set; }
        public Nullable<decimal> tio_time_order { get; set; }
        public Nullable<byte> tio_delete_flag { get; set; }
        public Nullable<System.DateTime> tio_add_date { get; set; }
        public string tio_add_user { get; set; }
        public Nullable<System.DateTime> tio_change_date { get; set; }
        public string tio_change_user { get; set; }
    
        public virtual co_organization co_organization { get; set; }
    }
}
