//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class score_x_request
    {
        public System.Guid scr_key { get; set; }
        public Nullable<System.Guid> scr_sow_key { get; set; }
        public Nullable<System.Guid> scr_rfp_key { get; set; }
        public string scr_section { get; set; }
        public string scr_value { get; set; }
        public Nullable<byte> scr_delete_flag { get; set; }
        public Nullable<System.DateTime> scr_add_date { get; set; }
        public string scr_add_user { get; set; }
        public Nullable<System.DateTime> scr_change_date { get; set; }
        public string scr_change_user { get; set; }
    
        public virtual rfp_request rfp_request { get; set; }
        public virtual rfp_scope_of_work rfp_scope_of_work { get; set; }
    }
}
