//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemMenu()
        {
            this.SystemMenu1 = new HashSet<SystemMenu>();
        }
    
        public int MenuID { get; set; }
        public string MenuName { get; set; }
        public string MenuIcon { get; set; }
        public string MenuIconAlt { get; set; }
        public string Notes { get; set; }
        public Nullable<int> MenuParentID { get; set; }
        public bool IsActive { get; set; }
        public string MenuLink { get; set; }
        public int MenuSeq { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemMenu> SystemMenu1 { get; set; }
        public virtual SystemMenu SystemMenu2 { get; set; }
    }
}
