//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class timeline
    {
        public System.Guid tim_key { get; set; }
        public Nullable<System.Guid> tim_rfp_key { get; set; }
        public Nullable<System.Guid> tim_rfr_key { get; set; }
        public Nullable<System.DateTime> tim_date { get; set; }
        public string tim_description { get; set; }
        public Nullable<byte> tim_completed_flag { get; set; }
        public Nullable<byte> tim_delete_flag { get; set; }
        public Nullable<System.DateTime> tim_add_date { get; set; }
        public string tim_add_user { get; set; }
        public Nullable<System.DateTime> tim_change_date { get; set; }
        public string tim_change_user { get; set; }
    }
}
